import { useMemo } from "react";
import { Link } from "react-router-dom";
import { useAuth } from "@/contexts/AuthContext";
import { useUserPlan, type Feature, type PlanoEfetivo } from "@/hooks/useUserPlan";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Separator } from "@/components/ui/separator";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Check, X, AlertTriangle, Crown, Award, CreditCard, Calendar, Clock, Mail, User as UserIcon, ShieldCheck, Sparkles, ArrowUpCircle, ArrowDownCircle, Info, Phone, Save, Loader2, ExternalLink } from "lucide-react";
import { cn } from "@/lib/utils";
import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import { useSearchParams } from "react-router-dom";
import IndiqueGanhe from "@/components/IndiqueGanhe";

type PlanKey = "ouro" | "prata" | "gratis";
interface PlanDef { key: PlanKey; nome: string; preco: number; precoDia: number; cor: string; icone: typeof Crown; destaque?: string; features: { label: string; ok: boolean }[]; }
const CHECKOUT_URLS: Record<Exclude<PlanKey, "gratis">, string> = { ouro: "https://pay.cakto.com.br/37myfzv_1077920", prata: "https://pay.cakto.com.br/vx5m9ao_1155374" };
const CAKTO_MANAGE_URL = "https://app.cakto.com.br/";
const PLANOS: PlanDef[] = [
  { key: "ouro", nome: "Aluno de Ouro", preco: 28.5, precoDia: 28.5 / 31, cor: "from-amber-400 via-yellow-500 to-amber-600", icone: Crown, destaque: "Mais completo", features: [{ label: "Estudar OQs nativos (Gerais e Especialidades) com MRE", ok: true }, { label: "Acesso completo a métricas detalhadas", ok: true }, { label: "Módulos de Estudo Focado: Crítico, Novo, Difíceis e Esquecidos", ok: true }, { label: "Gerar OQs por importação de planilha e por Inteligência Artificial (IA)", ok: true }, { label: "Direcionamento automático na Trilha Estratégica", ok: true }, { label: "Incorporar simulados à Trilha Estratégica", ok: true }, { label: "Acesso total a materiais de apoio e áudio aulas", ok: true }] },
  { key: "prata", nome: "Aluno de Prata", preco: 21.5, precoDia: 21.5 / 31, cor: "from-slate-300 via-slate-400 to-slate-500", icone: Award, features: [{ label: "Estudar OQs nativos (Gerais e Especialidades) com MRE", ok: true }, { label: "Acesso completo a métricas detalhadas", ok: true }, { label: "Módulos de Estudo Focado: Crítico, Novo, Difíceis e Esquecidos", ok: true }, { label: "Gerar OQs manualmente ou por importação de planilha", ok: true }, { label: "Gerar OQs por Inteligência Artificial (IA)", ok: false }, { label: "Direcionamento automático na Trilha Estratégica", ok: true }, { label: "Resumos, simulados e materiais de apoio", ok: false }] },
  { key: "gratis", nome: "Free Trial", preco: 0, precoDia: 0, cor: "from-zinc-500 via-zinc-600 to-zinc-700", icone: Sparkles, destaque: "14 dias de acesso Ouro", features: [{ label: "Todos os recursos do Aluno de Ouro durante 14 dias", ok: true }, { label: "Após 14 dias: conta congelada", ok: true }, { label: "Após 45 dias congelada: exclusão da conta e dos dados de desempenho", ok: true }] },
];
const fmt = (n: number) => n.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
const diasAte = (iso?: string | null) => iso ? Math.ceil((new Date(iso).getTime() - Date.now()) / 86400000) : null;
function planoToKey(p: PlanoEfetivo): PlanKey { return p === "ouro" ? "ouro" : p === "prata" ? "prata" : "gratis"; }

export default function MeuPlano() {
  const { user } = useAuth();
  const { plano, assinatura, refresh } = useUserPlan();
  const [pagamentos, setPagamentos] = useState<any[]>([]);
  const [perfil, setPerfil] = useState<{ nome?: string; foto_url?: string | null; whatsapp?: string | null } | null>(null);
  const [whatsapp, setWhatsapp] = useState("");
  const [savingWhatsapp, setSavingWhatsapp] = useState(false);
  const [searchParams, setSearchParams] = useSearchParams();
  const [confirmPlan, setConfirmPlan] = useState<PlanKey | null>(null);
  const [cancelDialogOpen, setCancelDialogOpen] = useState(false);
  const [canceling, setCanceling] = useState(false);
  const handleUpgrade = (key: PlanKey) => setConfirmPlan(key);
  const executePlanChange = (key: PlanKey) => { if (!user || key === "gratis" || !user.email) return; const url = new URL(CHECKOUT_URLS[key]); url.searchParams.set("email", user.email); if (perfil?.nome) url.searchParams.set("name", perfil.nome); if (perfil?.whatsapp) url.searchParams.set("phone", perfil.whatsapp.replace(/\D/g, "")); window.location.assign(url.toString()); };
  const formatWhatsapp = (value: string) => { const digits = value.replace(/\D/g, "").slice(0, 11); if (digits.length <= 2) return digits.length ? `(${digits}` : ""; if (digits.length <= 7) return `(${digits.slice(0, 2)}) ${digits.slice(2)}`; return `(${digits.slice(0, 2)}) ${digits.slice(2, 7)}-${digits.slice(7)}`; };
  const saveWhatsapp = async () => { if (!user) return; const digits = whatsapp.replace(/\D/g, ""); if (digits.length < 10) { toast.error("Digite um WhatsApp válido com DDD."); return; } setSavingWhatsapp(true); const { data, error } = await supabase.from("profiles").update({ whatsapp: digits }).eq("id", user.id).select("nome, foto_url, whatsapp").single(); setSavingWhatsapp(false); if (error) { toast.error("Não foi possível salvar seu WhatsApp."); return; } setPerfil(data); setWhatsapp(formatWhatsapp(data.whatsapp ?? digits)); toast.success("WhatsApp atualizado com sucesso."); };
  const cancelSubscription = () => { setCanceling(true); window.location.assign(CAKTO_MANAGE_URL); };
  useEffect(() => { document.title = "Meu plano — OQ MED"; }, []);
  useEffect(() => { if (searchParams.get("checkout") !== "success") return; toast.success("Pagamento confirmado!", { description: "Estamos ativando seu plano. Isso leva alguns segundos." }); let tries = 0; const iv = setInterval(() => { refresh(); tries++; if (tries >= 6) clearInterval(iv); }, 2500); const params = new URLSearchParams(searchParams); params.delete("checkout"); setSearchParams(params, { replace: true }); return () => clearInterval(iv); }, [searchParams, setSearchParams, refresh]);
  useEffect(() => { if (!user) return; supabase.from("pagamentos").select("*").eq("usuario_id", user.id).order("data_pagamento", { ascending: false }).limit(3).then(({ data }) => setPagamentos(data || [])); supabase.from("profiles").select("nome, foto_url, whatsapp").eq("id", user.id).maybeSingle().then(({ data }) => { setPerfil(data); setWhatsapp(formatWhatsapp(data?.whatsapp ?? "")); }); }, [user]);
  const planoAtualKey = useMemo(() => planoToKey(plano), [plano]);
  const { diasTrialRestantes, diasAteExclusao } = useUserPlan();
  const diasRenov = diasAte(assinatura?.proxima_renovacao);
  const alertaCritico = useMemo(() => { if (plano === "congelado" || plano === "gratis_expirado") { const dias = diasAteExclusao ?? 30; return { titulo: dias <= 7 ? "Atenção: seus dados serão apagados em breve" : "Sua conta está congelada", texto: dias <= 7 ? `Faltam ${Math.max(0, dias)} dia(s) para a exclusão permanente das suas métricas e dos OQs que você gerou. Reative sua assinatura para preservar tudo.` : `Você tem ${Math.max(0, dias)} dia(s) para reativar seu acesso antes que seus dados sejam removidos permanentemente.` }; } if (plano === "trial" && diasTrialRestantes !== null && diasTrialRestantes <= 3) return { titulo: "Seu período de teste está acabando", texto: `Restam ${Math.max(0, diasTrialRestantes)} dia(s) de trial. Escolha um plano para não perder seu progresso.` }; return null; }, [plano, diasTrialRestantes, diasAteExclusao]);
  const planoLabel: Record<PlanoEfetivo, string> = { trial: "Trial (14 dias de Ouro)", ouro: "Aluno de Ouro", prata: "Aluno de Prata", gratis: "Free Trial", gratis_expirado: "Conta Congelada", congelado: "Conta Congelada" };
  const planoBadgeCor: Record<PlanoEfetivo, string> = { trial: "bg-gradient-to-r from-amber-400 to-yellow-500 text-black", ouro: "bg-gradient-to-r from-amber-400 to-yellow-500 text-black", prata: "bg-gradient-to-r from-slate-300 to-slate-500 text-black", gratis: "bg-zinc-600 text-white", gratis_expirado: "bg-red-600 text-white", congelado: "bg-red-600 text-white" };
  return (<div className="container max-w-6xl mx-auto px-4 py-6 sm:py-10 space-y-8">
    <header className="space-y-1"><h1 className="text-2xl sm:text-3xl font-bold tracking-tight">Meu plano</h1><p className="text-sm text-muted-foreground">Gerencie sua assinatura, veja status e compare os planos disponíveis.</p></header>
    <section className="grid gap-4 md:grid-cols-2"><Card><CardHeader className="pb-3"><CardTitle className="flex items-center gap-2 text-base"><UserIcon className="h-4 w-4" /> Perfil</CardTitle></CardHeader><CardContent className="flex items-center gap-4"><Avatar className="h-14 w-14"><AvatarImage src={perfil?.foto_url ?? undefined} /><AvatarFallback>{(perfil?.nome ?? user?.email ?? "U").slice(0, 2).toUpperCase()}</AvatarFallback></Avatar><div className="min-w-0 flex-1 space-y-3"><div><p className="font-semibold truncate">{perfil?.nome ?? "Usuário"}</p><p className="text-xs text-muted-foreground flex items-center gap-1 truncate"><Mail className="h-3 w-3" /> {user?.email}</p></div><div className="space-y-2"><label htmlFor="profile-whatsapp" className="text-xs font-medium flex items-center gap-1.5"><Phone className="h-3.5 w-3.5 text-primary" /> WhatsApp para contato</label><div className="flex gap-2"><Input id="profile-whatsapp" inputMode="tel" autoComplete="tel" placeholder="(11) 99999-9999" value={whatsapp} onChange={(event) => setWhatsapp(formatWhatsapp(event.target.value))} className="h-9" /><Button type="button" size="icon" className="h-9 w-9 shrink-0" onClick={saveWhatsapp} disabled={savingWhatsapp} aria-label="Salvar WhatsApp">{savingWhatsapp ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}</Button></div><p className="text-[11px] text-muted-foreground">Usaremos este número para facilitar o suporte da sua assinatura.</p></div></div></CardContent></Card>
      <Card className="relative overflow-hidden"><div className={cn("absolute inset-x-0 top-0 h-1 bg-gradient-to-r", PLANOS.find(p => p.key === planoAtualKey)!.cor)} /><CardHeader className="pb-3"><CardTitle className="flex items-center gap-2 text-base"><ShieldCheck className="h-4 w-4" /> Plano atual</CardTitle></CardHeader><CardContent className="space-y-2"><Badge className={cn("text-sm px-3 py-1 font-semibold", planoBadgeCor[plano])}>{planoLabel[plano]}</Badge>{assinatura?.valor_mensal ? <p className="text-sm text-muted-foreground">Mensalidade: <strong className="text-foreground">{fmt(assinatura.valor_mensal)}</strong></p> : <p className="text-sm text-muted-foreground">Sem mensalidade ativa.</p>}<div className="flex flex-col gap-1"><p className="text-xs text-muted-foreground">Status: <span className="font-medium text-foreground capitalize">{assinatura?.status ?? "—"}</span></p>{assinatura?.cakto_customer_id && <p className="text-xs text-muted-foreground mt-1">Gestão da assinatura processada pela Cakto.</p>}</div></CardContent></Card></section>
    <section className="space-y-4"><div className="flex items-end justify-between flex-wrap gap-2"><div><h2 className="text-xl sm:text-2xl font-bold">Planos disponíveis</h2><p className="text-sm text-muted-foreground">Escolha o plano que melhor se encaixa na sua rotina de estudos.</p></div></div><div className="grid gap-4 md:grid-cols-3">{PLANOS.map(p => { const atual = planoAtualKey === p.key; const Icone = p.icone; return <Card key={p.key} className={cn("relative overflow-hidden flex flex-col", atual && "ring-2 ring-primary shadow-lg")}><div className={cn("absolute inset-x-0 top-0 h-1 bg-gradient-to-r", p.cor)} />{p.destaque && <div className={cn("absolute top-3 right-0 px-2 py-0.5 rounded-l-md text-[10px] font-bold text-white uppercase tracking-wider", p.key === "ouro" ? "bg-amber-600" : "bg-zinc-600")}>{p.destaque}</div>}<CardHeader><div className="flex items-center gap-2"><div className={cn("p-2 rounded-xl bg-gradient-to-br text-white", p.cor)}><Icone className="h-5 w-5" /></div><div><CardTitle className="text-lg">{p.nome}</CardTitle>{p.key !== "gratis" && <p className="text-xs text-muted-foreground">{fmt(p.preco)}/mês</p>}</div></div></CardHeader><CardContent className="flex-1 space-y-4"><div className="space-y-2">{p.features.map((f, i) => <div key={i} className="flex items-start gap-2 text-sm">{f.ok ? <Check className="h-4 w-4 text-emerald-500 shrink-0 mt-0.5" /> : <X className="h-4 w-4 text-muted-foreground/30 shrink-0 mt-0.5" />}<span className={cn(f.ok ? "text-foreground" : "text-muted-foreground/50")}>{f.label}</span></div>)}</div></CardContent><div className="p-6 pt-0 mt-auto">{p.key === "gratis" ? <Button variant="outline" className="w-full" disabled>Plano inicial</Button> : <Button className={cn("w-full font-bold", atual ? "bg-muted text-muted-foreground" : "bg-primary text-primary-foreground")} disabled={atual} onClick={() => handleUpgrade(p.key)}>{atual ? "Plano atual" : <><ExternalLink className="mr-2 h-4 w-4" /> {planoAtualKey === "ouro" || planoAtualKey === "prata" ? `Mudar para ${p.nome.replace("Aluno de ", "plano ")}` : `Assinar ${p.nome}`}</>}</Button>}</div></Card>; })}</div></section>
    <section className="grid gap-4 md:grid-cols-2"><Card><CardHeader className="pb-3"><CardTitle className="flex items-center gap-2 text-base"><Calendar className="h-4 w-4" /> Datas importantes</CardTitle></CardHeader><CardContent className="space-y-2 text-sm">{plano === "trial" && diasTrialRestantes !== null && <div className="flex items-center justify-between"><span className="text-muted-foreground">Fim do trial</span><span className="font-semibold">{Math.max(0, diasTrialRestantes)} dia(s)</span></div>}{assinatura?.proxima_renovacao && diasRenov !== null && <div className="flex items-center justify-between"><span className="text-muted-foreground">Próxima renovação</span><span className="font-semibold">em {Math.max(0, diasRenov)} dia(s)</span></div>}{diasAteExclusao !== null && (plano === "congelado" || plano === "gratis_expirado") && <div className="flex items-center justify-between text-destructive"><span className="flex items-center gap-1"><Clock className="h-3 w-3" /> Exclusão de dados</span><span className="font-semibold">em {Math.max(0, diasAteExclusao)} dia(s)</span></div>}{assinatura?.data_inicio_plano && <div className="flex items-center justify-between"><span className="text-muted-foreground">Início do plano</span><span className="font-medium">{new Date(assinatura.data_inicio_plano).toLocaleDateString("pt-BR")}</span></div>}{!assinatura?.proxima_renovacao && plano !== "trial" && diasAteExclusao === null && <p className="text-muted-foreground">Sem datas relevantes no momento.</p>}</CardContent></Card>
      <Card><CardHeader className="pb-3"><CardTitle className="flex items-center gap-2 text-base"><CreditCard className="h-4 w-4" /> Pagamento</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><div><p className="text-muted-foreground text-xs uppercase tracking-wide">Método atual</p><p className="font-medium">{assinatura?.metodo_pagamento ?? "Nenhum método cadastrado"}</p></div><Separator /><div><p className="text-muted-foreground text-xs uppercase tracking-wide mb-1">Últimos pagamentos</p>{pagamentos.length === 0 && <p className="text-muted-foreground">Sem histórico de pagamentos.</p>}{pagamentos.map(p => <div key={p.id} className="flex items-center justify-between py-1"><span>{new Date(p.data_pagamento).toLocaleDateString("pt-BR")} · {p.plano}</span><span className={cn("font-semibold", p.status === "pago" ? "text-emerald-500" : "text-destructive")}>{fmt(Number(p.valor))}</span></div>)}</div>{plano !== "trial" && <><Separator /><p className="text-[11px] text-muted-foreground text-center">Alterações e cancelamentos serão refletidos após confirmação da Cakto.</p><div className="pt-2 text-[10px] text-muted-foreground leading-relaxed italic border-t border-border/50 mt-2">Pagamentos processados com segurança. Cancele quando quiser. Após 45 dias de congelamento (inadimplência ou trial expirado), o sistema executa a exclusão irreversível da conta e dos dados de desempenho.</div>{assinatura?.status === "ativo" && assinatura.cakto_subscription_id && <Button variant="destructive" className="w-full mt-3" onClick={() => setCancelDialogOpen(true)}>Cancelar Assinatura</Button>}</>}</CardContent></Card></section>
    {(assinatura as any)?.cancel_at_period_end && assinatura?.proxima_renovacao && <Alert><AlertTriangle className="h-4 w-4" /><AlertTitle>Assinatura cancelada</AlertTitle><AlertDescription>Seu acesso premium continua ativo até {new Date(assinatura.proxima_renovacao).toLocaleDateString("pt-BR")}. Depois disso sua conta volta para o plano grátis.</AlertDescription></Alert>}
    {alertaCritico && <Alert variant="destructive" className="border-destructive/50"><AlertTriangle className="h-4 w-4" /><AlertTitle>{alertaCritico.titulo}</AlertTitle><AlertDescription>{alertaCritico.texto}</AlertDescription></Alert>}
    <section><IndiqueGanhe /></section>
    <Dialog open={cancelDialogOpen} onOpenChange={setCancelDialogOpen}><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle className="flex items-center gap-2"><AlertTriangle className="h-5 w-5 text-amber-600" />Tem certeza que deseja cancelar?</DialogTitle><DialogDescription>Antes de sair, queremos que você saiba exatamente o que acontece com sua preparação.</DialogDescription></DialogHeader><div className="space-y-3 py-2 text-sm"><Alert className="border-amber-200 bg-amber-50"><Info className="h-4 w-4 text-amber-600" /><AlertTitle className="text-amber-900">Seu progresso é valioso</AlertTitle><AlertDescription className="text-amber-800">Você pode manter seu plano ativo e continuar usando OQs, métricas, simulados e materiais para chegar mais preparado à residência. Se o motivo for financeiro ou dificuldade de rotina, considere falar com nosso suporte antes de sair.</AlertDescription></Alert><p className="text-muted-foreground">Ao confirmar, você será levado à área da Cakto para concluir o cancelamento com segurança. Depois do cancelamento, sua conta será <strong className="text-foreground">congelada</strong> quando o período contratado terminar: o acesso aos recursos premium será interrompido, mas seu histórico ficará preservado temporariamente.</p><p className="text-muted-foreground">Após <strong className="text-foreground">45 dias congelada</strong>, a conta e os dados de desempenho poderão ser excluídos permanentemente. Para não perder sua evolução, você precisará reativar a assinatura dentro desse prazo.</p></div><DialogFooter><Button variant="outline" onClick={() => setCancelDialogOpen(false)} disabled={canceling}>Continuar estudando</Button><Button variant="destructive" onClick={cancelSubscription} disabled={canceling}>{canceling ? "Abrindo Cakto..." : "Ir para cancelamento na Cakto"}</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={!!confirmPlan} onOpenChange={(open) => !open && setConfirmPlan(null)}><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle className="flex items-center gap-2">{confirmPlan && (planoAtualKey === "ouro" && confirmPlan === "prata" ? <ArrowDownCircle className="h-5 w-5 text-amber-600" /> : <ArrowUpCircle className="h-5 w-5 text-emerald-600" />)}Você tem certeza?</DialogTitle><DialogDescription>Você está escolhendo mudar de <strong>{planoLabel[plano]}</strong> para <strong>{confirmPlan && PLANOS.find(p => p.key === confirmPlan)?.nome}</strong>.</DialogDescription></DialogHeader><div className="space-y-4 py-2">{confirmPlan === "ouro" && <Alert className="border-emerald-200 bg-emerald-50"><Sparkles className="h-4 w-4 text-emerald-600" /><AlertTitle className="text-emerald-900">Estude com mais estratégia e chegue mais longe</AlertTitle><AlertDescription className="text-emerald-800">No Ouro, você desbloqueia a preparação completa: OQs gerados por IA, simulados integrados à Trilha Estratégica, materiais e áudio aulas, além de direcionamento automático para saber exatamente o que revisar e quando revisar. É mais clareza, consistência e tempo bem investido rumo à residência.</AlertDescription></Alert>}{confirmPlan === "prata" && planoAtualKey === "ouro" && <Alert className="border-amber-200 bg-amber-50"><Info className="h-4 w-4 text-amber-600" /><AlertTitle className="text-amber-900">O downgrade reduzirá seus recursos</AlertTitle><AlertDescription className="text-amber-800">No Prata, você perderá o acesso aos OQs por IA, aos simulados e aos materiais de apoio e áudio aulas. Esses recursos ajudam a identificar lacunas, revisar com eficiência e treinar para a prova de residência. Você ainda poderá fazer o downgrade, mas sua estratégia ficará mais limitada.</AlertDescription></Alert>}<p className="text-sm text-muted-foreground text-center italic">A cobrança e a ativação da mudança serão processadas pela Cakto. Você continuará com o plano atual até a confirmação da nova assinatura.</p></div><DialogFooter className="flex flex-col sm:flex-row gap-2"><Button variant="outline" onClick={() => setConfirmPlan(null)} className="flex-1">Voltar</Button><Button onClick={() => confirmPlan && executePlanChange(confirmPlan)} className="flex-1 bg-emerald-600 hover:bg-emerald-700">Continuar para a Cakto</Button></DialogFooter></DialogContent></Dialog>
  </div>);
}
