// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nlfdqokhrvcwukfxqrjx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sZmRxb2tocnZjd3VrZnhxcmp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODgzODkxNzEsImV4cCI6MjEwMzk2NTE3MX0.2KdJGpLid_Qp7LsF3Wvh40CsDrw80Nit4HohLjEEDPY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});